### ISSUE TITLE
No directory after a new install

### ISSUE THREAD

**Issue by AnTeBiOss** [balthisar/cncjs-pendant-gamepad#2]
Hello, 
here i got some new errors on a fresh install i strictly don't know how to solve ?? 

```
pi@raspberrypi:~/cncjs-pendant-gamepad $ bin/cncjs-pendant-gamepad.js -p /dev/ttyUSB0 -b 115200 -t grbl -vv run
node:internal/errors:465
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/home/pi/cncjs-pendant-gamepad/lib/console.js' imported from /home/pi/cncjs-pendant-gamepad/bin/cncjs-pendant-gamepad.js
    at new NodeError (node:internal/errors:372:5)
    at finalizeResolution (node:internal/modules/esm/resolve:437:11)
    at moduleResolve (node:internal/modules/esm/resolve:1009:10)
    at defaultResolve (node:internal/modules/esm/resolve:1218:11)
    at ESMLoader.resolve (node:internal/modules/esm/loader:580:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:294:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:80:40)
    at link (node:internal/modules/esm/module_job:78:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
pi@raspberrypi:~/cncjs-pendant-gamepad $ tsc
pi@raspberrypi:~/cncjs-pendant-gamepad $ bin/cncjs-pendant-gamepad.js -p /dev/ttyUSB0 -b 115200 -t grbl -vv run
cncjs-pendant-gamepad is currently running. Stop running with Control-C
Use 'cncjs-pendant-gamepad --help' if you're expecting to see something else here.
CNCpad  info GAMEPAD   attach Logitech Gamepad F710 (id 0)
CNCpad error CONNECTOR Error: ENOENT: no such file or directory, open '/home/pi/.cncrc'
CNCpad error CONNECTOR     at Object.openSync (node:fs:585:3)
CNCpad error CONNECTOR     at Module.readFileSync (node:fs:453:35)
CNCpad error CONNECTOR     at Connector.updateSecrets (file:///home/pi/cncjs-pendant-gamepad/lib/connector.js:125:42)
CNCpad error CONNECTOR     at Connector.connectServer (file:///home/pi/cncjs-pendant-gamepad/lib/connector.js:37:18)
CNCpad error CONNECTOR     at EventEmitter.<anonymous> (file:///home/pi/cncjs-pendant-gamepad/lib/connector.js:21:22)
CNCpad error CONNECTOR     at EventEmitter.emit (node:events:527:28)
CNCpad error CONNECTOR     at GamepadController.on (file:///home/pi/cncjs-pendant-gamepad/lib/gamepad_controller.js:141:25)
CNCpad error CONNECTOR     at new Connector (file:///home/pi/cncjs-pendant-gamepad/lib/connector.js:18:27)
CNCpad error CONNECTOR     at startCLI (file:///home/pi/cncjs-pendant-gamepad/lib/console.js:21:23)
CNCpad error CONNECTOR     at file:///home/pi/cncjs-pendant-gamepad/bin/cncjs-pendant-gamepad.js:12:1
CNCpad error CONNECTOR  Error: ENOENT: no such file or directory, open '/home/pi/.cncrc'
CNCpad error CONNECTOR     at Object.openSync (node:fs:585:3)
CNCpad error CONNECTOR     at Module.readFileSync (node:fs:453:35)
CNCpad error CONNECTOR     at Connector.updateSecrets (file:///home/pi/cncjs-pendant-gamepad/lib/connector.js:125:42)
CNCpad error CONNECTOR     at Connector.connectServer (file:///home/pi/cncjs-pendant-gamepad/lib/connector.js:37:18)
CNCpad error CONNECTOR     at EventEmitter.<anonymous> (file:///home/pi/cncjs-pendant-gamepad/lib/connector.js:21:22)
CNCpad error CONNECTOR     at EventEmitter.emit (node:events:527:28)
CNCpad error CONNECTOR     at GamepadController.on (file:///home/pi/cncjs-pendant-gamepad/lib/gamepad_controller.js:141:25)
CNCpad error CONNECTOR     at new Connector (file:///home/pi/cncjs-pendant-gamepad/lib/connector.js:18:27)
CNCpad error CONNECTOR     at startCLI (file:///home/pi/cncjs-pendant-gamepad/lib/console.js:21:23)
CNCpad error CONNECTOR     at file:///home/pi/cncjs-pendant-gamepad/bin/cncjs-pendant-gamepad.js:12:1 {
CNCpad error CONNECTOR   errno: -2,
CNCpad error CONNECTOR   syscall: 'open',
CNCpad error CONNECTOR   code: 'ENOENT',
CNCpad error CONNECTOR   path: '/home/pi/.cncrc'
CNCpad error CONNECTOR }

```

May you help me ?

**Comment by AnTeBiOss** [comment]
Hello, having some new messages : 

CNCpad  info CONNECTOR Sending open request for /dev/ttyACM0 at baud rate 115200

I'm unable tu run correctly the script 

Thanks for help
